name: umeng_common_sdk
description: 友盟+组件化基础库：Common Flutter plugin（Android & iOS）.
version: 1.2.2
homepage: https://www.umeng.com

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.umeng.umeng_common_sdk
        pluginClass: UmengCommonSdkPlugin
      ios:
        pluginClass: UmengCommonSdkPlugin